// clang-format off
// /include/roaring/roaring_version.h automatically generated by release.py, do not change by hand
#ifndef FERMAT_ROARING_INCLUDE_FERMAT_ROARING_VERSION
#define FERMAT_ROARING_INCLUDE_FERMAT_ROARING_VERSION
#define FERMAT_ROARING_VERSION "5.0.0"
enum {
    FERMAT_ROARING_VERSION_MAJOR = 5,
    FERMAT_ROARING_VERSION_MINOR = 0,
    FERMAT_ROARING_VERSION_REVISION = 0
};
#endif // FERMAT_ROARING_INCLUDE_FERMAT_ROARING_VERSION
// clang-format on