// Copyright (C) 2026 Kumo inc. and its affiliates. All Rights Reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
// AI: This file is a human/AI-readable summary of Fermat's public API and
// AI: design. Read this and docs/CONTAINERS.md instead of scanning all sources.
// AI: For kmcmake mechanics see docs/AI.md. For C++ style see
// AI: docs/c_cpp_project_rules.md.
//
// AI: Style: triple-slash Doxygen comments for all entries.

#pragma once

/// @defgroup fermat_library Fermat library
/// @brief In-process C++ containers (not bit codecs).
///
/// AI: Namespace fermat (Roaring C++: fermat::roaring).
/// AI: Link fermat::fermat_static. Includes from repo root: <fermat/...>.
/// AI: Out of scope: PFor/ZFP/bitstream codecs — other repository.
/// AI: Do not add robin-hood maps. Do not edit kmcmake/ unless asked.
/// AI: Do not glob/scan unrelated files; open the header named below.
/// @{

/// @brief Default unordered map/set (Swiss table, large tables)
/// AI: fermat::flat_hash_map / flat_hash_set
/// AI: #include <fermat/hashmaps/flat_hash_map.h>
/// AI: Lookup: find(), not operator[] (operator[] inserts).

/// @brief Tiny ordered-by-key map (HTTP query/header, few entries)
/// AI: fermat::vector_map  #include <fermat/maps/vector_map.h>
/// AI: Also vector_set, vector_multimap, vector_multiset.

/// @brief Pointer-stable hash
/// AI: fermat::node_hash_map / node_hash_set
/// AI: #include <fermat/hashmaps/node_hash_map.h>

/// @brief Insertion-order hash
/// AI: fermat::linked_hash_map / linked_hash_set
/// AI: #include <fermat/hashmaps/linked_hash_map.h>

/// @brief Ordered btree (range scan)
/// AI: fermat::btree_map / btree_set
/// AI: #include <fermat/maps/btree_map.h>
/// AI: Not ART — ART is byte-string only.

/// @brief HAT-trie (string prefix, dictionary)
/// AI: fermat::htrie_map / htrie_set
/// AI: #include <fermat/trie/hat/htrie_map.h>

/// @brief Adaptive Radix Tree
/// AI: fermat::Art<T>  #include <fermat/art/art.h>
/// AI: API: get/set/del(const char*). Inner node grow() deletes *this.
/// AI: Tests: tests/art/. Bench: benchmark/art/all_benchmark.cc

/// @brief Roaring integer sets
/// AI: fermat::roaring::Roaring, Roaring64, Roaring64Map
/// AI: #include <fermat/roaring/roaring.hpp>
/// AI: C++ wrappers; C sources compiled as .cc inside fermat library.
/// AI: Tests: tests/roaring/ GTest. Demos: examples/roaring/ (not tests).
/// AI: Bench: benchmark/roaring/benchmark.cpp — own main, not gbench.
/// AI: Dataset path: refs/CRoaring-master/benchmarks/realdata
/// AI: Do not change roaring library sources unless the user asks.

/// @brief Queue / list / memory
/// AI: chunked_queue, ring_buffer — <fermat/queue/chunked_queue.h>
/// AI: intrusive list — <fermat/list/intrusive_list.h>
/// AI: container_memory — <fermat/memory/container_memory.h>

/// @}

/// @defgroup project_summary Project Summary (kmcmake)
/// @brief Auto-generated by kmcmake build system
///
/// This section describes the project at a high level — ideal for AI assistants
/// to quickly understand purpose, architecture, and key conventions without
/// reading every source file.

/// @brief Project name (set during generation)
/// AI: The project name is fermat.
/// AI: Replace fermat with the actual project name in all docs/paths below.

/// @brief Build system
/// AI: Uses kmcmake (https://github.com/koomx/kmcmake) as the CMake framework.
/// AI: The build system is auto-generated from the kmcmake template.
/// AI: Framework modules live under kmcmake/ — DO NOT MODIFY.
/// AI: User configuration lives under cmake/ — MODIFY FREELY.

/// @brief Key design goals
/// AI: - Standardized C/C++ compilation across GCC/Clang/MSVC
/// AI: - Automatic SIMD detection and level control per CPU architecture
/// AI: - Thin user config layer (cmake/) for easy upgrades
/// AI: - Versioned framework (kmcmake/) that can be replaced on upgrade
/// AI: - Generated version.h provides build info + SIMD enable macros at compile time

/// @brief Directory layout
/// AI: .
/// AI: ├── CMakeLists.txt              # Entry point
/// AI: ├── .clang-format               # Default clang-format (WebKit-based)
/// AI: ├── cmake/                      # User configuration (modifiable)
/// AI: │   ├── <project>_user_option.cmake   # User overrides
/// AI: │   ├── <project>_cpm.cmake           # CPM deps (if KMCMAKE_USE_CPM)
/// AI: │   ├── <project>_deps.cmake          # Dependencies
/// AI: │   ├── <project>_cxx_config.cmake    # C++ flags aggregation
/// AI: │   ├── <project>_cpack_config.cmake  # Packaging config
/// AI: │   └── <project>_config.cmake.in     # CMake export template
/// AI: ├── kmcmake/                    # Framework (update-safe)
/// AI: │   ├── kmcmake_module.cmake    # Entry point
/// AI: │   ├── kmcmake_option.cmake    # Global options
/// AI: │   ├── arch/                   # Per-CPU SIMD detection + level
/// AI: │   └── tools/                  # Build functions + CPM.cmake
/// AI: ├── <project>/                  # Source code
/// AI: │   ├── CMakeLists.txt
/// AI: │   ├── *.h / *.cc
/// AI: │   ├── version.h (generated)
/// AI: │   └── skills.h (this file)
/// AI: ├── docs/                       # AI.md, c_cpp_project_rules.md, upgrades
/// AI: ├── tests/
/// AI: ├── benchmark/
/// AI: └── examples/

/// @brief Build flow
/// AI: 1. project() sets name + version
/// AI: 2. include(kmcmake_module) loads all framework modules
/// AI: 3. include(<project>_user_option OPTIONAL) — user overrides
/// AI: 4. include(<project>_deps) — optional CPM, then find_package deps
/// AI: 5. include(<project>_cxx_config) — sets KMCMAKE_CXX_OPTIONS
/// AI: 6. configure_file(version.h.in) — generates version.h
/// AI: 7. add_subdirectory(<project>) — builds main sources
/// AI: 8. add_subdirectory(tests) / benchmark / examples — optional

/// @brief SIMD architecture
/// AI: Detection is per-CPU-architecture, each in arch/<arch>/:
/// AI:   - kmcmake_arch_detect.cmake: probes hardware, exports KMCMAKE_<ARCH>_HAS_<FEAT>
/// AI:   - kmcmake_arch_level.cmake: reads KMCMAKE_RUNTIME_SIMD_LEVEL, exports:
/// AI:       KMCMAKE_ARCH_ENABLE_<FEAT>  (0/1 for version.h)
/// AI:       KMCMAKE_SIMD_CXX_FLAGS       (compiler flags)
/// AI: To override: set KMCMAKE_ARCH_ENABLE_<FEAT> to OFF in user_option.cmake
/// @}

/// @defgroup build_api CMake Build API
/// AI: All target types are defined in kmcmake/tools/. See docs/AI.md for demos.
/// @{
/// @brief kmcmake_cc_library   — static + shared lib from same objects
/// @brief kmcmake_cc_interface — header-only library
/// @brief kmcmake_cc_binary    — executable
/// @brief kmcmake_cc_object    — object library (no link)
/// @brief kmcmake_cc_test      — test executable + ctest registration
/// @brief kmcmake_cc_benchmark — benchmark executable
/// @brief kmcmake_cc_xxd       — embed static assets as std::string_view
/// @}

/// @defgroup config_vars Configuration Variables
/// AI: Output variables available after include(<project>_cxx_config)
/// @{
/// @brief KMCMAKE_BASE_CXX_FLAGS  — compiler flags determined by compiler ID
/// @brief KMCMAKE_SIMD_CXX_FLAGS  — SIMD flags from arch detection
/// @brief KMCMAKE_RANDEN_FLAGS    — AES/hardware random flags
/// @brief KMCMAKE_CXX_OPTIONS     — aggregated flags (BASE + SIMD + RANDEN)
/// @brief KMCMAKE_ARCH_ENABLE_*   — per-feature SIMD enable as 0/1 integers
/// @}

/// @defgroup version_header Generated version.h Macros
// The version.h file is generated from fermat/version.h.in
// and contains the following compile-time macros:
/// @{
/// @brief FERMAT_VERSION_MAJOR / _MINOR / _PATCH  — version components
/// @brief FERMAT_VERSION_STRING  — e.g. "0.0.5"
/// @brief FERMAT_SIMD_LEVEL  — target SIMD level string
/// @brief FERMAT_SIMD_ENABLE_SSE..AVX512F  — 0 or 1 per feature
/// @brief FERMAT_CXX_COMPILER_ID     — compiler name
/// @brief FERMAT_CXX_COMPILER_VERSION — compiler version
/// @brief FERMAT_BUILD_TYPE_STRING       — Debug/Release/etc
/// @brief FERMAT_BUILD_SYSTEM        — OS distro name
/// @brief FERMAT_GIT_COMMIT_HASH     — full git commit
/// @brief FERMAT_GIT_VERSION_STRING  — "tag-hash[-dirty]"
/// @}

/// AI: Read docs/CONTAINERS.md for container selection.
/// AI: Read docs/c_cpp_project_rules.md for C/C++ style and edit discipline.
/// AI: End of skills.h — prioritize this file over reading all source files.
